kind: Secret
apiVersion: v1
metadata:
  name: dials-backend-secrets
  namespace: cms-dials-prod
type: Opaque
data:
  DJANGO_SECRET_KEY:
  DJANGO_REDIS_URL:
  DJANGO_DATABASE_URI:
  DJANGO_KEYCLOAK_CONFIDENTIAL_CLIENT_ID:
  DJANGO_KEYCLOAK_CONFIDENTIAL_SECRET_KEY:
  DJANGO_KEYCLOAK_API_CLIENTS:
  DJANGO_OMS_SSO_CLIENT_ID:
  DJANGO_OMS_SSO_CLIENT_SECRET:
  DJANGO_KEYTAB_PWD:
  DJANGO_KEYTAB_USR:
