kind: Secret
apiVersion: v1
metadata:
  name: dials-etl-secrets
  namespace: cms-dials-prod
type: Opaque
data:
  CELERY_BROKER_URL:
  CELERY_RESULT_BACKEND:
  CELERY_REDBEAT_URL:
  DATABASE_URI:
  CERT_FPATH:
  KEY_FPATH:
  RAW_LAYERS:
  FLOWER_BASIC_AUTH:
  ETL_CONFIG_FPATH:
  MODEL_REGISTRY_PATH:
