kind: Secret
apiVersion: v1
metadata:
  name: redis-web-cache
  namespace: cms-dials-prod
type: Opaque
data:
  database-password:

---
kind: Secret
apiVersion: v1
metadata:
  name: redis-etl-broker
  namespace: cms-dials-prod
type: Opaque
data:
  database-password:
